
export const ADD_MORE_MUSICS = "ADD_MORE_MUSICS";

export const INITIAL_MUSICS = "INITIAL_MUSICS";

export const CHANGE_MUSIC_PAGE = "CHANGE_MUSIC_PAGE";

export const SEARCH_MUSICS = "SEARCH_MUSICS";

export const ADD_FAVOURITE = "ADD_FAVOURITE";

export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE";

export const INITIAL_FAVOURITES = "INITIAL_FAVOURITES"